# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gfs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tgfs.proto\x12\x03gfs\"\x14\n\x06String\x12\n\n\x02st\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"#\n\x12HealthCheckRequest\x12\r\n\x05lease\x18\x01 \x01(\t\"%\n\x13HealthCheckResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"*\n\x16PrimaryToClientRequest\x12\x10\n\x08\x63lientid\x18\x01 \x01(\t2\x8f\x02\n\x14MasterServerToClient\x12\'\n\tListFiles\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12(\n\nCreateFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12(\n\nAppendFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12)\n\x0b\x43reateChunk\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12&\n\x08ReadFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12\'\n\tWriteFile\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x32\xfe\x01\n\x13\x43hunkServerToClient\x12$\n\x06\x43reate\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12+\n\rGetChunkSpace\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12$\n\x06\x41ppend\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12\"\n\x04Read\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12%\n\x07\x41\x64\x64\x44\x61ta\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x12#\n\x05Write\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x32\x46\n\x06Health\x12<\n\x05\x43heck\x12\x17.gfs.HealthCheckRequest\x1a\x18.gfs.HealthCheckResponse\"\x00\x32\x37\n\x0fPrimaryToClient\x12$\n\x06\x43ommit\x12\x0b.gfs.String\x1a\x0b.gfs.String\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gfs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STRING._serialized_start=18
  _STRING._serialized_end=38
  _EMPTY._serialized_start=40
  _EMPTY._serialized_end=47
  _HEALTHCHECKREQUEST._serialized_start=49
  _HEALTHCHECKREQUEST._serialized_end=84
  _HEALTHCHECKRESPONSE._serialized_start=86
  _HEALTHCHECKRESPONSE._serialized_end=123
  _PRIMARYTOCLIENTREQUEST._serialized_start=125
  _PRIMARYTOCLIENTREQUEST._serialized_end=167
  _MASTERSERVERTOCLIENT._serialized_start=170
  _MASTERSERVERTOCLIENT._serialized_end=441
  _CHUNKSERVERTOCLIENT._serialized_start=444
  _CHUNKSERVERTOCLIENT._serialized_end=698
  _HEALTH._serialized_start=700
  _HEALTH._serialized_end=770
  _PRIMARYTOCLIENT._serialized_start=772
  _PRIMARYTOCLIENT._serialized_end=827
# @@protoc_insertion_point(module_scope)
